my:
  greeting: Hello World from config server ravi333
  list: one,two,three,four
  
db:
   connection: "{connectionString: 'with config server ravi333', userName: 'foo', password: 'pass3'}"
   host: 127.0.0.2
   port: 33300
