my:
  greeting: Hi, Getting configurations from centralized config server .48 8888
  list: one,two,three,four

db:
   connection: "{connectionString: 'with config server ravi333', userName: 'foo', password: 'pass3'}"
   host: 127.0.0.2
   port: 33300

spring:
      datasource:
                url: "jdbc:oracle:thin:@135.254.161.41:1523:emfdb424"
                username: emfdbuser
                password: emfdbuser
      jpa:
         show-sql: true
         properties:
                   hibernate:
                            use_sql_comments: true
                            format_sql: true
                            dialect: org.hibernate.dialect.Oracle10gDialect
                            type: trace

logging:
       level:
            org:
               hibernate:
                        SQL: DEBUG
                        type: trace
                        descriptor:
                                  sql:
                                     BasicBinder: TRACE
